sonar.projectKey=cohort-9-dotnet-7771-ashhal
sonar.working.directory=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend
sonar.pullrequest.cache.basepath=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend

7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.projectKey=cohort-9-dotnet-7771-ashhal:7170C0A0-6AAB-4B8C-A024-518EA66C5392
7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.projectName=TaskManagement.Core
7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.projectBaseDir=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core
7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.sourceEncoding=utf-8
7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.tests=
7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.sources=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Class1.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\DTOs\\TaskFilterDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Helpers\\PasswordHasher.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Interfaces\\IAuthService.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Interfaces\\IDashboardService.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Interfaces\\ITaskRepository.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Interfaces\\ITaskService.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Interfaces\\IUserRepository.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Interfaces\\IUserService.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Models\\JwtSettings.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Models\\Task.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Models\\User.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Services\\AuthService.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Services\\DashboardService.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Services\\TaskService.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\Services\\UserService.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\obj\\project.assets.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\obj\\TaskManagement.Core.csproj.nuget.dgspec.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\bin\\Debug\\net8.0\\TaskManagement.Core.deps.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Core\\obj\\Debug\\net8.0\\TaskManagement.Core.sourcelink.json"

7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.cs.analyzer.projectOutPaths=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\0"
7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.cs.roslyn.reportFilePaths=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\0\\Issues.json"
7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.cs.scanner.telemetry=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\0\\Telemetry.json"

7170C0A0-6AAB-4B8C-A024-518EA66C5392.sonar.working.directory=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\.sonar\\mod0
1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.projectKey=cohort-9-dotnet-7771-ashhal:1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B
1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.projectName=TaskManagement.Infrastructure
1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.projectBaseDir=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure
1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.sourceEncoding=utf-8
1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.tests=
1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.sources=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\obj\\project.assets.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\obj\\TaskManagement.Infrastructure.csproj.nuget.dgspec.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\bin\\Debug\\net8.0\\TaskManagement.Infrastructure.deps.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\bin\\Debug\\net8.0\\TaskManagement.Infrastructure.runtimeconfig.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\obj\\Debug\\net8.0\\TaskManagement.Infrastructure.sourcelink.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\Class1.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\Data\\ApplicationDbContext.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\Data\\DesignTimeDbContextFactory.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\Migrations\\20260803105138_InitialCreate.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\Migrations\\20260803105138_InitialCreate.Designer.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\Migrations\\ApplicationDbContextModelSnapshot.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\Repositories\\TaskRepository.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Infrastructure\\Repositories\\UserRepository.cs"

1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.cs.analyzer.projectOutPaths=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\1"
1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.cs.roslyn.reportFilePaths=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\1\\Issues.json"
1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.cs.scanner.telemetry=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\1\\Telemetry.json"

1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B.sonar.working.directory=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\.sonar\\mod1
32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.projectKey=cohort-9-dotnet-7771-ashhal:32D16B6A-8F69-4456-9647-E4C290E8AE8B
32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.projectName=TaskManagement.API
32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.projectBaseDir=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API
32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.sourceEncoding=utf-8
32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.tests=
32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.sources=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\appsettings.Development.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\appsettings.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\obj\\project.assets.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\obj\\TaskManagement.API.csproj.nuget.dgspec.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\Properties\\launchSettings.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\bin\\Debug\\net8.0\\TaskManagement.API.deps.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\bin\\Debug\\net8.0\\TaskManagement.API.runtimeconfig.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\obj\\Debug\\net8.0\\TaskManagement.API.sourcelink.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\Controllers\\AuthController.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\Controllers\\DashboardController.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\Controllers\\TasksController.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\Controllers\\UsersController.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\AuthResponseDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\CreateTaskDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\DashboardStatsDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\LoginDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\RegisterDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\TaskDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\TaskFilterDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\TaskResponseDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\UpdateProfileDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\UpdateTaskDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\DTOs\\UserProfileDto.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\Middleware\\ExceptionMiddleware.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\Program.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\Validation\\NotInPastAttribute.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\obj\\Debug\\net8.0\\TaskManagement.API.GlobalUsings.g.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\obj\\Debug\\net8.0\\TaskManagement.API.AssemblyInfo.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\obj\\Debug\\net8.0\\TaskManagement.API.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.API\\TaskManagement.API.http"

32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.cs.analyzer.projectOutPaths=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\2"
32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.cs.roslyn.reportFilePaths=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\2\\Issues.json"
32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.cs.scanner.telemetry=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\2\\Telemetry.json"

32D16B6A-8F69-4456-9647-E4C290E8AE8B.sonar.working.directory=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\.sonar\\mod2
164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.projectKey=cohort-9-dotnet-7771-ashhal:164C7683-78EF-4485-A1BF-C8ABC46005EA
164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.projectName=TaskManagement.Tests
164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.projectBaseDir=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests
164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.sourceEncoding=utf-8
164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.sources=
164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.tests=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\obj\\project.assets.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\obj\\TaskManagement.Tests.csproj.nuget.dgspec.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\bin\\Debug\\net8.0\\TaskManagement.API.deps.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\bin\\Debug\\net8.0\\TaskManagement.API.runtimeconfig.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\bin\\Debug\\net8.0\\TaskManagement.Tests.deps.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\bin\\Debug\\net8.0\\TaskManagement.Tests.runtimeconfig.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\obj\\Debug\\net8.0\\TaskManagement.Tests.sourcelink.json",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\JwtSettingsTests.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\PasswordHasherTests.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\TaskServiceTests.cs",\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\TaskManagement.Tests\\UnitTest1.cs"

164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.cs.analyzer.projectOutPaths=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\3"
164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.cs.roslyn.reportFilePaths=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\3\\Issues.json"
164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.cs.scanner.telemetry=\
"C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\3\\Telemetry.json"

164C7683-78EF-4485-A1BF-C8ABC46005EA.sonar.working.directory=C:\\IBA\\10Pearls Internship\\cohort-9-dotnet-7771-ashhal\\backend\\.sonarqube\\out\\.sonar\\mod3
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/obj/**,**/bin/**,**/Migrations/**,**/*.Designer.cs
sonar.organization=ashhalaamir
sonar.visualstudio.enable=false

sonar.modules=7170C0A0-6AAB-4B8C-A024-518EA66C5392,1ED1BA99-642E-4485-BDB6-A0BB8BE49B7B,32D16B6A-8F69-4456-9647-E4C290E8AE8B,164C7683-78EF-4485-A1BF-C8ABC46005EA

